name: coptix
description: "Coptix App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
#  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: AvenirArabic
    fonts:
    - asset: assets/fonts/AvenirArabic-Book.otf
    - asset: assets/fonts/AvenirArabic-Heavy.otf
    - asset: assets/fonts/AvenirArabic-Light.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
