name: coptix
description: Coptix App.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  provider: ^6.1.1
  logger: ^2.0.2+1
  device_preview: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  share: ^2.0.4
  form_validator: ^2.1.1
  fluttertoast: ^8.2.4
  debounce_throttle: ^2.0.0
  tuple: ^2.0.2
  hive: ^2.2.3
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/

  fonts:
  - family: AvenirArabic
    fonts:
    - asset: assets/fonts/AvenirArabic-Book.otf
    - asset: assets/fonts/AvenirArabic-Heavy.otf
    - asset: assets/fonts/AvenirArabic-Light.otf
